### PR TITLE
[WIP] Life in an octane world

### LINKED ISSUE #201: What does this addon look like in an `@tracked`/Octane world?
A placeholder issue to start a discussion around this topic. I'll do some exploration myself and build some context around it here soon. But anyone else interested in diving in is welcome to make a start on it too.

### Brain dump

These functions are going to be related to this:

https://github.com/adopted-ember-addons/ember-launch-darkly/blob/bbe2fe0b96a884fcf6746f39d3fa38b3f8a09ac0/addon/services/launch-darkly.js#L44-L69

This might come in to play too:

https://github.com/adopted-ember-addons/ember-launch-darkly/blob/bbe2fe0b96a884fcf6746f39d3fa38b3f8a09ac0/addon/helpers/variation.js#L25

As is this Babel plugin (potentially, and hopefully, not needed in an `@tracked` world):

https://github.com/adopted-ember-addons/ember-launch-darkly/blob/master/babel-plugin/index.js

### PR DESCRIPTION
**Pull request by achambers**
Exploring what life in an `@tracked` world might look like.

Closes #201 

## TODO

- [x] `initialize` and `variation` functions
- [x] `identify` function
- [x] `variation` template helper
- [x] Bootstrap with local flags
- [x] Streaming flags
- [x] Running locally against local flags
- [x] Running tests with all flags false by default
- [x] `withVariation` test helper
- [x] Helpers to manipulate flags from JS console
- [x] README
- [x] Migration docs
- [x] Add event source polyfill
- [x] Run in local mode in dev
- [x] Make `window.__LD__.get(key, defaultValue)` work (ie, implement the default value bit)
- [x] Implement `window.__LD__.user`
- [x] Move to use release-it for releasing the addon
- [x] Correct Ember version number in compatibility chart in README
- [x] Handle "default value" of flag if it doesn't exist and consider using `variationDetail` [LINK](https://github.com/launchdarkly/js-sdk-common/blob/master/src/index.js#L251)
- [ ] Remove babel-plugin-tester and any other libs that were installed for the babel transform
    - ember-code-snippet
    - ember-prism

## TO CONSIDER
- [ ] `initialize` is async - can we get to a place where we can run this in app.js (and so, flags be available in initializers etc)? (Feels like we need "top-level await" but unsure)
- [ ] Codemod to update things that have changed
- [x] In README, add a note about `sendEventsOnlyForVariation` and how we're setting it to `true` but it can be overridden in the LD config
- [ ] How does bootstrapping work with an error connecting to LD service? Does it fallback to those bootstrapped values?
- [ ] If bootstrapping is used, does this mean that the LD client will be available for use immediately and could this be what allows us to initialize in the `app.js`?
- [x] Handle default flag value and if the flag doesn't exist on LD
- [ ] Use mirage to stub out the calls to LD and help simulate things like a 500 from the service?
- [x] Default flag values for flags used in tests that aren't defined in `localFlags`
- [x] How to avoid needing to `await settled` in a test after using `withVariation` in order to see the updates flush. The old code used test waiters in the `variation` template helper, but I'm not clear on how that works with `@tracked`
- [x] Do we need to implement `withVariation` so it can be `await`ed?
- [ ] Does this work in fastboot? Should it?
- ~How do we get `variation` JS function to re-evaluate streamed flags when used inside an `@computed` getter? Not sure how to get the computed to re-computed as we can't add the dependent key for re-computation.~ I think the recommendation is that you don't. `@tracked` is a replacement for CP's and so we should look for a way to do the same thing with tracking. Changes to a tracked getter do not recompute a CP so not a lot we can do.

### CODE REVIEW

**Comment by cadeParade** [comment]
Hiya, 
The developments in this PR seem super exciting! Thank you so much for working on this. 

I see above that among the list of considerations is fastboot support. I am in the process of converting our app to support fastboot in a limited way and it turns out this addon is not compatible. The offender is [this import line](https://github.com/adopted-ember-addons/ember-launch-darkly/pull/225/files#diff-58b72023aca64b2a589aa59de4a8f212f60dc717fb57735b69b0a7f676b5bfe2R4). This line imports the launch darkly js library which uses client-side js concepts like `window` liberally. Fastboot cannot parse these things because it is not running in a browser. Even when nothing in the app is asking for the launch darkly service, the import itself is problematic for fastboot.

To get around this, fastboot docs recommend this: https://ember-fastboot.com/docs/addon-author-guide#third-party-dependencies . And here is an example of an addon adding conditional imports based on fastboot: https://github.com/smashweaver/ember-cli-dragula-shim/pull/1/files .
I need my app to work in the mean time so I'll play around with what it might look like to support fastboot for this addon. If I can get something to work I'll open a PR!

Thanks again for your efforts!

**Comment by achambers** [comment]
> Hiya,
> The developments in this PR seem super exciting! Thank you so much for working on this.
> 
> I see above that among the list of considerations is fastboot support. I am in the process of converting our app to support fastboot in a limited way and it turns out this addon is not compatible. The offender is [this import line](https://github.com/adopted-ember-addons/ember-launch-darkly/pull/225/files#diff-58b72023aca64b2a589aa59de4a8f212f60dc717fb57735b69b0a7f676b5bfe2R4). This line imports the launch darkly js library which uses client-side js concepts like `window` liberally. Fastboot cannot parse these things because it is not running in a browser. Even when nothing in the app is asking for the launch darkly service, the import itself is problematic for fastboot.
> 
> To get around this, fastboot docs recommend this: [ember-fastboot.com/docs/addon-author-guide#third-party-dependencies](https://ember-fastboot.com/docs/addon-author-guide#third-party-dependencies) . And here is an example of an addon adding conditional imports based on fastboot: [smashweaver/ember-cli-dragula-shim#1 (files)](https://github.com/smashweaver/ember-cli-dragula-shim/pull/1/files) .
> I need my app to work in the mean time so I'll play around with what it might look like to support fastboot for this addon. If I can get something to work I'll open a PR!
> 
> Thanks again for your efforts!

Hi @cadeParade. Thanks for stopping by.

To be honest, I've not considered fastboot at all in this addon to date due to not having been using fastboot.

Having said that, it is something that it should absolutely support.

I spoke with @samselikoff (who I believe you're working with on this) last night. He said he'd also start looking in to it (with you I presume).

I'm not really in a position to tackle fastboot support right now but I am more than happy to help and support your efforts in it.

Have a look, as you suggested, and get back to me here with some details and heopfully we can make a plan of attack.

**Comment by esbanarango** [comment]
@achambers 👋 . Do we know what's the status here

**Comment by achambers** [comment]
> @achambers 👋 . Do we know what's the status here

Yep. #235 is where this is being implemented proper. I'm going to be merging that PR to a beta 2x branch and publishing the beta to npm in the next day or so so that I can test it against my production app before shipping 2.0.

**Pull request closed without merging**
