### PR TITLE
Add persist method

### PR DESCRIPTION
**Pull request by alexis-falaise**
This MR adds a `persist` method to the Context class, allowing to make persistent the current set of flags in their current state.

- They will be saved to local storage, and retrieved on the following initialization.
- Persisted feature flags can also be reset using the `resetPersistence` method (or simply by calling `localStorage.removeItem('ember-launch-darkly')` in the console

### CODE REVIEW

**Comment by alexis-falaise** [comment]
cc. @SkoebaSteve

**Review by SkoebaSteve — COMMENTED** [review]
So if I understand it correctly, the user will have to set localStorage based flags in the browser by having them as a JSON parsed string in the `ember-launch-darkly` key.

If we have flags setup like this for example:

```
{
  booleanFlag: true,
  stringFlag: 'hello'
}
```

If I want to persist on setting `stringFlag` to another value, I first need to parse the string, update the specific and then set it back using `JSON.stringify` for the whole object.

I was thinking if we can make it simpler for the user to just use `window.__LD__.set('stringFlag', 'goodbye')` as we do for [current localFlags](https://github.com/adopted-ember-addons/ember-launch-darkly#local-feature-flags) but we do the heavy lifting for them to save it to the store.

We might need to have a different mode, maybe `localStorage` instead of `local`?

**Comment by alexis-falaise** [comment]
The mechanics are relying on the localStorage as you described, with one nuance:
- If you have flags locally persisted and make new changes, you'll just need to call the `window.__LD__.persist()` method once to persist the new state of the flags set

It's an explicit approach to persistence, making developers aware of when persistence occurs.
We can definitely explore having a more systematic approach with a new `localStorage` mode too :)

**Comment by SkoebaSteve** [comment]
> * If you have flags locally persisted and make new changes, you'll just need to call the `window.__LD__.persist()` method once to persist the new state of the flags set.

Ah so you mean that we if we do the following the changes will be saved to localStorage.

```javascript
//setting the flag
window.__LD__.set('stringFlag', 'goodbye')
window.__LD__.persist()
```

I am not necessarily against that, could be a good alternative to ship firs

**Comment by alexis-falaise** [comment]
@SkoebaSteve should we move forward with merging this first iteration ?

**Comment by aoumiri** [comment]
> We might need to have a different mode, maybe localStorage instead of local?

I like this simple API, you define your feature flags in the __LD__ object as usual, and if you like a certain configuration you just freeze it in localStorage using `.persist()`.

@SkoebaSteve I think we can move on with this explicit `persist()` approach as good first iteration, and then we can explore alternatives such as a localStorage mode.

**Comment by tniezurawski** [comment]
Doesn't this feature lack documentation?

**Pull request merged**
