### PR TITLE
adhoc: support deferred clientSideId and possibly secure mode?

### PR DESCRIPTION
**Pull request by rstudner**
Thus, one wouldn’t have to put the clientSideId into the config/environment.js

The UI could hit an API endpoint, or possibly even the response body from a login, and then do something like this:
```
    return get(this, 'launchDarkly').initialize(userStuffHere, {
       clientSideId: FROM_THE_SERVER,
       hash: ALSO_FROM_THE_SERVER
    );
```

### CODE REVIEW

**Comment by achambers** [comment]
@rstudner We're doing a push to get this repo up to date and published as v1.0. Will get to this PR soon hopefully. You will see that `master` is not using Ember 3.11 so we're moving forward.

Just wanted to reach out and let you know that this is not ignored or abandoned. I'll be in touch when we switch focus to this PR.

**Comment by rwwagner90** [comment]
@achambers how are things going on this effort? Anything we can help with?

**Comment by achambers** [comment]
@rwwagner90 `master` includes a bunch of changes bringing this repo up to Ember 3.11 with a bunch of improvements, bug fixes, dependency updates etc.

Have not yet bumped the LD js client but I'm very keen to get to that soon.

I'd not published `master` just yet as I was testing it on my own production app to ensure it's all ok (which it does seem to be). However, I've been meaning to publish it as a 1.0.0-beta.1 but have just not got there.

I'll endeavour to do that tomorrow.

As for this specific PR, I've not yet been able to cast my focus to it due to the above changes first.

If you have interest in upgrading the LD client js, I'd love to accept a PR for that. Other than that, most of the things I wanted to get to have landed in `master` already. So, you could yarn install from there for the time being until I publish the beta release if you want to move forward.

**Comment by rwwagner90** [comment]
@achambers thanks for the update! Is everything in master now? If so, I am happy to help try to update the LD client.

**Comment by achambers** [comment]
@rwwagner90 said:
> @achambers thanks for the update! Is everything in master now? If so, I am happy to help try to update the LD client.

Confirm on `master`. As I said, I'll endeavour to publish it tomorrow as `v1.0.0-beta.1`.

As for the LD client, that'd be super ace if you were interested in running with it. It is severely behind. We recently updated it to the last version in the pre 1.x series. But I'd say bumping to the 2.x series might need some closer attention. I've skimmed the changelogs and I'm pretty sure there are one or two things there we care about. But it's been a while and have not given it deep thought yet.

I'd be more than happy to act as a sounding board or help you out with this if you were willing to drive it.

Let me know your thoughts on that.

**Comment by rwwagner90** [comment]
I can definitely take a look. I think it is on our radar to help out with this addon as part of our work, but not for at least a couple weeks probably.

**Comment by achambers** [comment]
> I can definitely take a look. I think it is on our radar to help out with this addon as part of our work, 

That'd be ace mate. Would be much appreciated. Would be great to have someone else who's using it in anger to bounce ideas off too.

> but not for at least a couple weeks probably.

No hassles.

**Comment by achambers** [comment]
Hi @rwwagner90 . I've published `master` as [`v1.0.0-beta.0`](https://github.com/ember-launch-darkly/ember-launch-darkly/releases/tag/v1.0.0-beta.0)

**Review by jaredgalanis — APPROVED** [review]
Thanks for this! This is now rebased and combines the documentation from #144. I think given the optionality we can merge and follow up if further support is required.

**Pull request merged**
