### PR TITLE
🔖 V2

### PR DESCRIPTION
**Pull request by achambers**

### CODE REVIEW

**Comment by pzuraq** [comment]
this is looking good! Need any help to get it over the line? We're about to adopt launch-darkly and could definitely use this 😄

**Comment by achambers** [comment]
@pzuraq said:
> this is looking good! Need any help to get it over the line? We're about to adopt launch-darkly and could definitely use this 😄

Hi Chris 👋 I've been running the v2 beta in our production app for a couple of months now and everything looks fine so this PR should defo be good to go.

Thanks for the nudge. I'll ship this to master and release a v2.0.0 shortly. At this stage, it'll be tomorrow.

**Comment by acorncom** [comment]
@achambers thought I'd ping you to see if you needed a hand in wrapping this up? About to start using launch darkly on a client project and this looks lovely 😄

**Comment by achambers** [comment]
We finally got there. Thanks for being sooooo patient folks. And thanks for the nudge @acorncom 

https://github.com/adopted-ember-addons/ember-launch-darkly/releases/tag/v2.0.0

/cc @pzuraq

**Comment by achambers** [comment]
That'd be ace @acorncom . Will do. Thanks a mil 😄

**Comment by achambers** [comment]
On an unrelated note, I'm super happy with how this PR worked out and how much simpler tracked properties make this addon and mental model. Hopefully things are much easier to reason about now.

**Pull request merged**
